### ISSUE TITLE
Fresh install error: supertype not defined

### ISSUE THREAD

**Issue by adidion91** [JunoLab/atom-julia-client#206]
I have installed a fresh copy of atom/julia and the console within atom will not run anything.
Even given a simple "2+2", I get an error "UndefVarError: supertype not defined".

The Julia terminal (outside atom) works, but atom's julia terminal is entirely crippled. 

The error looks the same as in #178, but the resolutions used in that issue did not help:
https://github.com/JunoLab/atom-julia-client/issues/178

Thanks!

**Comment by MikeInnes** [comment]
I've fixed this up, you just need to Pkg.update().

**Comment by ChandramouliBanerjee** [comment]
Same here, Pkg.update() doesn't solve the issue. I am running Atom/Juno on Ubuntu 16.04.

**Comment by MikeInnes** [comment]
What's the output of Pkg.status()? I just tagged Media.jl v0.2.1 so you should check you're on that.

**Comment by adidion91** [comment]
Can confirm the issue is fixed, thanks Mike! Chandra, make sure you are calling Pkg.update() from the Julia terminal, not the terminal inside Atom.
