### ISSUE TITLE
0.5 ASCIIString is deprecated

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#212]
I get this warning in the console during autocomplete:
```
WARNING: Base.ASCIIString is deprecated, use String instead.
  likely near /Users/solver/Projects/julia-client/script/boot.jl:327
```

**Comment by dlfivefifty** [comment]
Some more:

```
WARNING: Base.Abs2Fun is deprecated, use Base.#abs2 instead.
  likely near /Users/solver/Projects/julia-client/script/boot.jl:327
WARNING: Base.AbsFun is deprecated, use Base.#abs instead.
  likely near /Users/solver/Projects/julia-client/script/boot.jl:327
```

**Comment by dlfivefifty** [comment]
It didn't give any more information, so its hard to tell where its coming from

**Comment by MikeInnes** [comment]
Yeah that is a difficulty. If they're getting in the way you can also turn depwarns off completely.

**Comment by dlfivefifty** [comment]
How?

**Comment by MikeInnes** [comment]
It's one of the options in the julia-client settings.

**Comment by pfitzseb** [comment]
This is fixed on CodeTools master (see https://github.com/JunoLab/CodeTools.jl/commit/04cd5aded8c3b7a2f45e4559b2e889428375f071).

**Comment by dlfivefifty** [comment]
This looks like its still an issue when you change the module.

**Comment by pfitzseb** [comment]
True. [Should Be Fixed Now™](https://github.com/JunoLab/CodeTools.jl/commit/baffedca98f8ab781cbd86b461cb7252cd35e8c8).
