### ISSUE TITLE
Documentation toggle doesn't work

### ISSUE THREAD

**Issue by xukai92** [JunoLab/atom-julia-client#221]
The documentation toggle doesn't work for me and show below for any functions.

![image](https://cloud.githubusercontent.com/assets/5985769/18111060/8625a638-6f14-11e6-91f0-84fc4594d582.png)

**Comment by pfitzseb** [comment]
This is fixed in the new version.

**Comment by xukai92** [comment]
@pfitzseb Hi I still see the same issue after updating just now.

**Comment by pfitzseb** [comment]
Did you `Pkg.update()`?

**Comment by xukai92** [comment]
Yes, I'm currently reinstalling juno & Julia to see if it will be fixed.

**Comment by xukai92** [comment]
A clean install of juno & julia solved this problem. Thx.
