### ISSUE TITLE
UTF8String error after Julia 0.5.0 update and ink, julia update in Atom

### ISSUE THREAD

**Issue by GeoHubX** [JunoLab/atom-julia-client#238]
I am using Julia 0.5.0, Atom 1.10.2 with the ink update to 0.5.2 and julia-client 0.5.5 on Windows 10 (if that matters).
I precompiled Atom by entering "using Atom" in the Julia console as discussed in other strings, but still get errors in the Atom console, but different ones than before when starting Julia in that environment:

require(Symbol) in module Base
WARNING: Base.UTF8String is deprecated, use String instead.
  likely near C:\Users\testy.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.UTF8String is deprecated, use String instead.
  likely near C:\Users\testy.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.UTF8String is deprecated, use String instead.
  likely near C:\Users\testy.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.UTF8String is deprecated, use String instead.
  likely near C:\Users\testy.atom\packages\julia-client\script\boot.jl:327

.\boot.jl does not have 327 lines, so I do not know where to look to insert a quick fix.

**Comment by pfitzseb** [comment]
This might already be fixed on CodeTools master... if not, then it's probably one of our dependencies not being up to date for you? Did you `Pkg.update()` recently? Does `Pkg.status()` show any pinned packages?

**Comment by GeoHubX** [comment]
Sebastian,

 

Thanks for getting back to me.

 

I run Pkg.update() regularly.

 

I am not sure what you mean by pinned, but when I run Pkg.status() the following is the only package with a note beside the name.

 

- Atom                          0.5.2              1465f3cb (dirty)

 

Julia is actually working in the Atom environment, but must be making the override from UTF8String to String in order to run, given the change in Julia 0.5.0 to simplify the use of strings. I expect the capability to make the override will be removed as this becomes the stabile version.

 

-Nick

**Comment by pfitzseb** [comment]
The thing is that we don't seem to have `UTF8String` anywhere in our code, so I'm not sure where that's coming from. Are you getting other deprecation errors or are those the only ones?

Also, you might want to `Pkg.free("Atom")` sometime because you have changes there that are not in the release (also so [here](http://docs.julialang.org/en/latest/manual/packages/#checkout-pin-and-free)).

**Comment by GeoHubX** [comment]
I tried Pkg.free, Pkg.rm, and Pkg.checkout but cannot rid myself of the version of Atom installed. The error says it is “dirty,” whatever that means.

**Comment by GeoHubX** [comment]
I got rid of the troublesome version. Which version of Atom would you recommend I pin, if any?

**Comment by pfitzseb** [comment]
None, the latest version (meaning whatever the package manager gives you after `Pkg.update()`) should be working fine.
We'll try to make sure it stays that way :)

**Comment by GeoHubX** [comment]
Atom calls Gallium at start-up, which is unstable in win32, unfortunately, so it still doesn't work for me, although I'm getting closer. I'll keep trying. In the meantime, I can use IJulia/Jupyter, but I like to be able to use both interfaces, as they are good for different things.

**Comment by pfitzseb** [comment]
Does unstable mean that it doesn't work at all?

**Comment by GeoHubX** [comment]
Yes. It fails to load.Nicholas ManganaroOn Sep 22, 2016 6:05 PM, Sebastian Pfitzner <notifications@github.com> wrote:Does unstable mean that it doesn't work at all?
