### ISSUE TITLE
MethodError: no method matching lookup(::StackFrame)

### ISSUE THREAD

**Issue by RauliRuohonen** [JunoLab/atom-julia-client#314]
With julia-client 0.5.12 and Julia 0.5.1-pre+55, I get this error:

    MethodError: no method matching lookup(::StackFrame)
    Closest candidates are:
      lookup(!Matched::UInt64) at stacktraces.jl:137
      lookup(!Matched::Ptr{Void}) at stacktraces.jl:125
     in yieldto(::Task, ::ANY) at event.jl:136
     in wait() at event.jl:169
     in wait(::Condition) at event.jl:27
     in wait(::Task) at task.jl:132
     in macro expansion at dynamic.jl:67 [inlined]
     in (::Atom.##63#66)(::Dict{String,Any}) at eval.jl:96
     in handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N}) at comm.jl:163
     in (::Atom.##14#17)() at event.jl:68

when running this Julia code in the console:

    import Gadfly
    Gadfly.plot(eye(2))

To be sure, that is not the correct way to use Gadfly's plot command, but it shouldn't crash either. Trying to enter another command in the console after this hangs forever.

**Comment by HephaestusTheIndolent** [comment]
I get the exact same message, character for character, in an entirely different context. julia-client 0.5.12 with Julia 0.5.0. 

Just started coding something requiring opening .mat files along filepaths. Whenever I try to evaluate: 

`path = "C:\\Users\\MyName Buffer\\Documents\\MATLAB\\FPE Dissertation\\Simulations\\s201\\p02\\Dt00_tf30\\SPH_c01\\sigT3\\U1_E1_B1_N1473\\"`

I get in console
`ArgumentError: \x used with no following hex digits in "C:\\Users\\MyName Buffer\\Documents\\MATLAB\\FPE Dissertation\\Simulations\\s201\\p02\\Dt00_tf30\\SPH_c01\\sigT"`

Along with the same Julia Client - Internal Error 

`MethodError: no method matching lookup(::StackFrame)
Closest candidates are:
  lookup(!Matched::UInt64) at stacktraces.jl:137
  lookup(!Matched::Ptr{Void}) at stacktraces.jl:125
 in yieldto(::Task, ::ANY) at event.jl:136
 in wait() at event.jl:169
 in wait(::Condition) at event.jl:27
 in wait(::Task) at task.jl:132
 in macro expansion at dynamic.jl:67 [inlined]
 in (::Atom.##63#66)(::Dict{String,Any}) at eval.jl:96
 in handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N}) at comm.jl:163
 in (::Atom.##14#17)() at event.jl:68`

This ONLY occurs when the filepath is of the specific length where truncation in the argument error occurs (i.e. at "sigT"); changing the order of the folders say causes truncation at the same index in the string regardless of content. E.g. 

`path = "C:\\Users\\MyName Buffer\\Documents\\MATLAB\\FPE Dissertation\\Simulations\\s201\\p02\\Dt00_tf30\\SPH_c01\\U1_E1_B1_N1473\\SigT3\\"`

`ArgumentError: \x used with no following hex digits in "C:\\Users\\MyName Buffer\\Documents\\MATLAB\\FPE Dissertation\\Simulations\\s201\\p02\\Dt00_tf30\\SPH_c01\\U1_E"`


I can get around this by using the raw string literal macro to declare to the path  (shown here [http://stackoverflow.com/questions/21882353/raw-literal-strings-in-julia](url) ) but when I try to load .mat files that have similarly long file paths the same exact errors are generated. 

NONE of this happens when executing the exact same code in the Julia terminal, only in the Atom/Juno IDE. 

Atom command line also hangs forever requiring a manual stop/restart of Julia to continue doing anything.

**Comment by pfitzseb** [comment]
The errors reported by @HephaestusTheIndolent have been fixed by https://github.com/JunoLab/Juno.jl/commit/3eb7dbad3971b576f65e1042c561886bcfa48c16 (which fixes the underlying string display error) and https://github.com/JunoLab/Atom.jl/commit/26a850cf55e0c40e16b080ff2c95b55a913434a8 (after which Juno remains useable when encountering a display error).

@RauliRuohonen Can you check if your issue persists on the master branches of Juno.jl and Atom.jl?

**Comment by HephaestusTheIndolent** [comment]
I just did a package update and attempted it again. 

I still get the same error as before but it no longer freezes atom/Juno and I can continue using it. So the Atom fix has been propagated but the Juno.jl fix apparently hasn't as of this posting.

**Comment by pfitzseb** [comment]
Yeah, we didn't release a new version of Juno.jl yet, so there's no chance for you to have the fix without being on the master branch.
