### ISSUE TITLE
"Powershell not spawned"

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-julia-client#35]
I get an error now (on master) saying "'powershell' could not be spawned.  Is it installed on your path", with a sidebar opening with error

Window load time: 1219ms
events.js:141 Uncaught Error: spawn powershell ENOENT

**Comment by one-more-minute** [comment]
cc @Varanas

**Comment by Varanas** [comment]
Yay, I broke it...
@dlfivefifty What OS are you on? I'd guess it's a Linux since `process.plattform` [seems to be problematic there](https://github.com/JunoLab/atom-julia-client/issues/17).
But I'm installing a Linux as I write, so hopefully I'll be able to debug this soonish.

**Comment by SergeUK** [comment]
I am on windows 10.

**Comment by Varanas** [comment]
And you have the same problem with spawning Powershell, @SergeUK?

**Comment by SergeUK** [comment]
I don’t think so but to be honest with you I don’t really know how to try to spawn Powershell.

**Comment by MichaelHatherly** [comment]
Ran across this as well this morning. Changing the order of the `process.platform` switches to check for `win32` first and default to `linux` seems to fix this on archlinux and windows 7 for me. 

```diff
diff --git a/lib/connection/process.coffee b/lib/connection/process.coffee
index 93d9cd5..049909e 100644
--- a/lib/connection/process.coffee
+++ b/lib/connection/process.coffee
@@ -35,24 +35,24 @@ module.exports =
 
   spawnJulia: (port) ->
     switch process.platform
-      when 'darwin' || 'linux'
-        @proc = process.spawn(@jlpath(), [@jlargs()..., '-e', "import Atom; @sync Atom.connect(#{port})"])
-      else
+      when 'win32'
         @proc = process.spawn("powershell", ["-ExecutionPolicy", "bypass", "& \"#{__dirname}\\spawnInterruptibleJulia.ps1\" -port #{port} -jlpath \"#{@jlpath()}\" -jloptions \"#{@jlargs().join(' ')}\""])
+      else
+        @proc = process.spawn(@jlpath(), [@jlargs()..., '-e', "import Atom; @sync Atom.connect(#{port})"])
 
   interruptJulia: ->
     switch process.platform
-      when 'darwin' || 'linux'
-        @proc.kill('SIGINT')
-      else
+      when 'win32'
         @sendSignalToWrapper('SIGINT')
-
+      else
+        @proc.kill('SIGINT')
 
   killJulia: ->
-    if process.platform != 'darwin' && process.platform != 'linux'
-      @sendSignalToWrapper('KILL')
-    else
-      @proc.kill()
+    switch process.platform
+      when 'win32'
+        @proc.kill()
+      else
+        @sendSignalToWrapper('KILL')
 
   sendSignalToWrapper: (signal) ->
     wrapper = net.connect(port: 26992)
diff --git a/lib/julia-client.coffee b/lib/julia-client.coffee
index 1fcd948..b03716d 100644
--- a/lib/julia-client.coffee
+++ b/lib/julia-client.coffee
@@ -16,10 +16,10 @@ defaultTerminal =
   switch process.platform
     when 'darwin'
       'Terminal.app'
-    when 'linux'
-      'x-terminal-emulator -e'
-    else
+    when 'win32'
       'cmd /C start cmd /C'
+    else
+      'x-terminal-emulator -e'
 
 module.exports = JuliaClient =
   config:
```

**Comment by Varanas** [comment]
Yeah, thought so. For some reason I thought that `process.platform` was behaving strangely on windows as well, but it works for me too.

**Comment by MichaelHatherly** [comment]
Cool, I'll PR that diff in a moment.

**Comment by Varanas** [comment]
Sweet, thanks!

**Comment by MichaelHatherly** [comment]
It's a bit weird that `process.platform` on linux was underfined and not for other platforms... is there an upstream repo tracking this issue already? I've not managed to find one yet.

**Comment by dlfivefifty** [comment]
It’s fixed for now  (OS X).  Thanks!

**Comment by hustf** [comment]
@Varanas , I get the same message now, on Windows 10, and am ready to report details.

I have already tried various fixes of course. So this is not the start.
1) As a normal user, Atom seemed not have permission to start Julia.
2) I changed this user to have administrator privileges. Started up, and got success. Too optimistic, though.
3) On successive starts, I get no success. Start atom from the powershell -> Ctrl+Shift+P-> Julia client open console - > type e.g. homedir()

A red pop-up, says:
    'powershell' could not be spawned. Is it installed and on your path? If so, please open an issue
    on the package spawning the process.

I have two warnings and two messages:

    Warning: /deep/  combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
    Warning: ::shadow     C:\Users\F\Appdata\Local\atom\app-1.3.1\resources\app.asar\src\text-editor-component.js:915 pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
    Error:   Uncaught Error: spawn powershell ENOENT     event.js:141


Events.js is this: chrome-devtools://devtools/bundled/events.js
I can't seem to find it though, and I don't know this debugging tool.
...


Atom packages:
ink 0.1.1
julia-client 0.1.2
language-julia 0.4.1

Julia packages:
Atom 0.2.0+
CodeTools 0.2.0+
JuliaParser 0.6.3+

**Comment by Varanas** [comment]
@hustf: Strange. Can you start powershell from a terminal? Also, you are on `atom-julia-client` master, right?

**Comment by hustf** [comment]
I can start powershell from a terminal. When I do, the Ms-dos prompt changes to PS C:\users....
I am probably not on julia-client master, but how to check that?

**Comment by Varanas** [comment]
You did not follow the instructions from [here](https://github.com/JunoLab/atom-julia-client/blob/master/docs/README.md) when installing, right? Otherwise you wouldn't have any issues with powershell, methinks.

If so, it's just a matter of checking out the latest master, switching to that branch and restarting Atom.

Also, if that doesn't work: Is there more to that backtrace in the developer console (`ctrl+alt+i`)? I'm kinda puzzeled why Atom can't spawn ps...

**Comment by hustf** [comment]
Not quite, but I have read it. Regarding installation instructions, I looked at all the relevant places I could find first. I might end up building the whole thing. I made a new user, with fresh installations of Anaconda, Julia, the basic packages, github desktop, Visual Studio Code, updated python, even made sure to make an environment variable with visual studio version 2015. And PATH.

Then I followed 
https://github.com/JunoLab/atom-julia-client/blob/master/docs/README.md#developer-install

I rebooted and Git shell - > cd julia-client -> atom ->console and got quite another error message. This time the error message was regarding an error in Ink. I ought to upgrade to Ink 0.1.2 according to the error message, which had something to do with strings. Sorry the details were lost on me. I tried to update from within Atom, but got feedback that everything is up to date. Still at Ink 0.1.1 though.

I am now unable to reproduce any of the errors. Everything works fine, at the moment. If there is an error log stored somewhere, I can provide it of course.

**Comment by hustf** [comment]
OK, all I had to do to reproduce was double-clicking a .jl file. I am back at 'powershell could not be spawned', and will try to proceed slowly with digging up this. The most effective way is probably that I answer your questions, starting wtih ctrl+alt+i.

**Comment by hustf** [comment]
ctrl+alt+i just opens the debugging interface from which I reported the errors above. 

I don't understand why it matters in which github local directory I am when launching Atom?

**Comment by Varanas** [comment]
How does that matter? You're getting no errors when launching from a certain directory?

Also, did you get that ink error again?

**Comment by hustf** [comment]
Yes? If that in deed explains why it works sometimes.

Just now I have an erroneous instance of Atom open, which I opened by double-clicking a .jl file. I do not know how to use this tool and find the contents of varable ENOENT (if it is a variable?).

The ink error has not reappeared.

**Comment by hustf** [comment]
Also, I have a normal Julia instance open. If that matters?

**Comment by hustf** [comment]
It can also be of interest what I have in my Julia-client settings:
Julia Arguments: Default: -q
Julia Path: C:\Users\F\AppData\Local\Julia-0.4.2\bin\julia.exe
Notifications: On
Terminal Command used to open a terminal:
cmd \c 
(I have experimented with all of these settings)

**Comment by hustf** [comment]
I do not know if Atom opens as completely separate instances. If they do, I can of course test simultaneously by starting from the git shell command line in this Julia-client folder.

**Comment by Varanas** [comment]
Nope, shouldn't matter. In those sessions where you weren't getting that error, did you have a julia file open or started Julia from within Atom?

**Comment by Varanas** [comment]
Oh, wait. You were starting from the git shell? That might explain things. Could you try starting Atom with the shortcut or from the normal terminal (and opening a `*.jl` file and executing something in it so Juno tries to start julia)?

**Comment by hustf** [comment]
In order to check if this caused the issiue, I tried: 1) No power shell. 2) Power shells with active Julia sessions inside them. 3) Starting Atom directly on its .exe shortcut.

I will proceed to do what you told.

**Comment by Varanas** [comment]
Also, you might want to try to start up a normal julia session from the terminal and typing `;powershell \$PSVersionTable.PSVersion`.

**Comment by hustf** [comment]
There are two ways to start Atom directly: Atom Command and Atom Desktop App.

I try Desktop App. No messages. Then open a .jl file. Go to line 1+1. Ctrl+enter. And Fail, powershell thingie.

Atom Run Command (Windows-button, type Atom and you get both alternatives. Same procedure, same fail.

A normal Julia REPL is open in the background.

**Comment by hustf** [comment]
shell> powershell \$PSVersionTable.PSVersion
    Major  Minor  Build  Revision
    -----  -----  -----  --------
    5      0      10586  0

**Comment by Varanas** [comment]
Mkay. I'm confused.
Next thing you could try: Open the dev interface in atom and type
```
cp = require('child_process')
cp.spawn("powershell")
```
into the console there. That will probably fail as well...

**Comment by hustf** [comment]
Will do. Just want to mention, when I start Julia from Git Shell and do the shell powershell check, I get the same powershell build.

**Comment by hustf** [comment]
Sorry, how do I open the dev interface? I know about ctrl+shift+p, and about the julia console.

**Comment by Varanas** [comment]
Ah, I meant the `ctrl+alt+i` thingie ;)

**Comment by hustf** [comment]
cp = require('child_process')
    Object {}
    cp.spawn("powershell")
    ChildProcess {domain: null, _events: Object, _eventsCount: 0, _maxListeners: undefined, _closesNeeded: 3...}

(we can't copy from the console, I have to retype)

**Comment by Varanas** [comment]
So it didn't error?!

Does `cp.spawnSync("powershell", ["$PSVersionTable.PSVersion.Major"]).output[1].toString()` give `5` as a result (you can actually copy from that console, btw)?

**Comment by hustf** [comment]
Yes. "5 " (copied)

**Comment by Varanas** [comment]
Hm. I am even more confused.
I quite honestly don't know how or why this happens -- the last snippet should be exactly the one  where it fails when it tries to start julia.

**Comment by hustf** [comment]
I have a hunch now. No explanation, but a hunch.
Every time I started Atom above, a certain .jl file was open. 
C:\Users\F\.julia\v0.4\GraphLayout\test\runtests.jl

I tried many times to close it, and start a new file. Then close atom. And open it again. This file was present at reopen. Finally, I double-clicked another .jl-file. And now I'm stuck with this file instead.

And with no errors.

So has this to do with another package? Language-julia or ink?

**Comment by Varanas** [comment]
That's intended, I think. Atom remembers the file you had opened last and opens that again when restarting.

**Comment by hustf** [comment]
I've tried with 8-10 different files now.
I seem to get malfunction every time the startup-file is part of the julia packages.
And every .jl file outside it seems to work.
Is Atom colliding with github or something?

**Comment by hustf** [comment]
The above 'mystery fix' allowed me to work for a while, although I am not sure what works as intended (I can't make Julia REPL a visible application, it's always a hidded process). 

The issue of this thread may be may be a symptom of the below, which I'll post on Julia issue tracker if I find it's not been reported already:

0.4.2 behaves differently from 0.4.1 with respect to shell commands. The behaviour is different depending on context, but here is an example:

From a git shell, Julia 0.4.1/bin, I can run Julia.exe and the shell commands 'ls', 'dir' and 'powershell \$PSVersionTable.PSVersion' work fine.

In the same window, it quit() Julia, then move to the 0.4.2/bin folder, start Julia.exe and get this:

    shell> ls
    7z.dll (.....)
    shell> dir
    **ERROR: could not spawn `dir`: no such file or directory (ENOENT)
     in _jl_spawn at process.jl:262**
    shell> powershell \$PSVersionTable.PSVersion
    Major  Minor  Build  Revision
    -----  -----  -----  --------
    5      0      10586  0

**Comment by hustf** [comment]
We haven't got to the core of this here; this post is a follow-up from my side. Atom-julia-client is potentially great, but on my system it's not quite there yet.

https://groups.google.com/forum/#!topic/julia-users/pHonnw8X3iw

**Comment by hustf** [comment]
This seems to fix the issue with Julia 0.4.2 when git desktop is installed, and your git desktop shell preference is the powershell and not the old ms-dos style shell. The shell commands don't generally work.
Atom editor ->Packages->Settings View->Manage packages->Julia client->Settings->Terminal
Replace the default CMD \C by:
c:\users\YOURUSERNAMEHERE\documents\GitHub\GitHub.appref-ms --open-shell

**Comment by Varanas** [comment]
So you're saying that changing the `terminal` setting of `atom-julia-client` helps? 

Just to make sure I understood you correctly earlier:
  - You start Atom, load a `.jl` file.
  - If you then start the julia client, either by doing `Ctrl+J Ctrl+S`, by evaluating something in the editor or by evaluating something in the console, you get the `'powershell' could not be spawned.` error.
  - You restart Atom, change the `terminal` setting to the github shell, open the same `*.jl` file as above and again start Julia as above, you get no error? Or were you trying to open a REPL via `Ctrl+J Ctrl+R`?

Also, I'm going to reopen this until I understand how this was solved and what we should improve to fix this.

**Comment by hustf** [comment]
Varanas, I corrected the path in the previous post, and tried to make the text more clear. I should also have mentioned that I set my Julia path to end with 'Julia.exe'. Not the intended use, but a dirty fix. 

With these settings, I somehow bypassed the Julia / Git bug that makes me unable to run shell commands from 0.4.2. But I am not so far able to start a REPL client with these settings. Instead, I get a git/powershell when pressing ctrl+(j r)

I hope the above is clear now, and I will try to answer your questions precisely if I get more time tonight.

**Comment by hustf** [comment]
In my case, changing the terminal settings AND the julia path seemed to help, compared to some other combinations I tried. But having trouble to reproduce fully today, I see this is likely to be per chance.

Now with all three default settings (and Julia.exe on my PATH variable):
 * Start atom with a .jl file loaded AND a project file in the left tab. This matters.
 * ctrl+enter works. Restarting in the same way and pressing ctrl + (j s) yields a progress indicator for some seconds, which disappears. No output at all. ctrl+alt+i reveals the error message below. Note that Pkgdep.js is NOT a package or github folder. (This just happens sometimes, on a retry for checking it does not happen.) Evaluating something in the console works. But shell commands like ;ls or ;dir yield the second error message below. 
 * I restart atom, change the terminal setting (only) to C:\Users\F\AppData\Local\GitHub\GitHub.appref-ms --open-shell. ctrl+enter in a .jl file works. Restarting, the ctrl+(j s) yields a progress indicator for some seconds, which disappears. ctrl+alt+i reveals just the two deprecation warnings that's always there. Evaluation works (with no wait). Shell commands do NOT work. 
   
I probably tested all the various methods julia console commands yesterday, including starting Julia 'manually' (ctrl+(j+r), type julia in the git shell, type 'using atom', test the shell command ;ls (which works). But today, I am not able to make the connection back to Julia-atom-client. I can not make shell commands run from the atom-client-console, or get a visible REPL started automatically. Changing the default terminal parameter /C to /K will at least keep console visible, and this may help with debugging further.







Error message from bullet point 2. After this, I log off my windows accout and back on.
    Error: Cannot find module 'C:\Users\F\PkgdepVis\src\PkgdepVis.jl\spec'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\F\AppData\Local\atom\app-    1.3.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\F\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
    at requireSpecs (C:\Users\F\AppData\Local\atom\app-1.3.1\resources\app.asar\spec\jasmine-test-runner.js:101:7)
    at module.exports (C:\Users\F\AppData\Local\atom\app-1.3.1\resources\app.asar\spec\jasmine-test-runner.js:49:7)
    at module.exports (C:\Users\F\AppData\Local\atom\app-1.3.1\resources\app.asar\src\initialize-test-window.js:88:17)
    at setupWindow (file:///C:/Users/F/AppData/Local/atom/app-1.3.1/resources/app.asar/static/index.js:85:5)
    at window.onload (file:///C:/Users/F/AppData/Local/atom/app-1.3.1/resources/app.asar/static/index.js:40:9)

Second error message from bullet point 2. 
    could not spawn 'dir': no such file or directory (ENOENT) in jl.spawn at base\process.jl:262

**Comment by Varanas** [comment]
FWIW, I saw that error today as well. And I couldn't reproduce it.

I'm afraid I still don't quite understand what's wrong here...

**Comment by Varanas** [comment]
@hustf Just something that came to mind today: Are you on a slow computer? I've noticed some spurious errors that may be related to system load -- they occur much more often on my laptop than on my desktop machine.

The REPL-spawning problem should be fixed with https://github.com/JunoLab/atom-julia-client/pull/71.

**Comment by hustf** [comment]
@varanas , thanks for not giving up. #71 seems to have fixed the REPL-spawning problem!

The issue here was reported from a pretty decent 64 bit computer, just recently upgraded to Windows 10. Also with the julia Atom package in a precompiled state.

I bought a new gamer's laptop a week ago, with Windows 10. First thing I did was keep tongue-in-cheek and install Julia (Juno bundle and the command-line version), and follow the developer recipe. The PATH is already quite swollen in that state, but Atom and Julia just have to cope with that (in the future). Some PATH entries end in "\" and some not. I tried a bit of twiddling with PATH endings, and checked that process.env.path reported the same as in the operating system (Julia->ENV["PATH"] is different.)

I was not able to neither spawn a REPL or run Julia in the background - until just now. Will try it out now.

**Comment by hustf** [comment]
The REPL spawning works now.
Also, starting a REPL client works (ctrl+alt +j+r). The window caption reads exactly:

````
C:\windows\system32\cmd.exe - "C:\Users\F\AppData\Local\Julia-0.4.2\bin\julia.exe" -q -P "import Atom;Atom.connect(51884)"
````


(starting took some time, for recompiling CodeTools). The REPL client lives on after Atom is closed. The settings were :  
    -q 
   C:\Users\F\AppData\Local\Julia-0.4.2\bin\julia.exe

Ctrl + j+s does not work, same old powershell spawn issue. There is a long history of similar issues.

With all three julia-client settings field equal to defaults, the response is exactly the same but the window caption is just
    C:\Windows\System32\cmd.exe

I find this confusing: Why include Julia.exe at the end of the second setting? It would be more intuitive if the directory path had to be given when the julia PATH entry is missing.

**Comment by Varanas** [comment]
Alright, so you can at least use Atom now, except for the built-in console. :)

I'm afraid the powershell issue still baffles me, especially since you can spawn it from the dev-console in Atom.

**Comment by hustf** [comment]
In deed, this is the way I would work anyway. I've always worked in an IDE before and produce a lot faster given this kind of environment, so thank you very much!

**Comment by Varanas** [comment]
@hustf There is now an option to use Juno without the `powershell` wrapper on master. You might wanna try that and see if it helps you.

**Comment by hustf** [comment]
Hello, Varanas, 

I have been meaning to report that powershell option started working. Unfortunately, I can`t say exactly why it did. The PATH variable seems to be split in two: Environment variables for your account, and system environment variables. It may also matter for some parser whether one ends the preceding folder names with or without a \ at the end - unix style. 

Even though my path is now more ok, I`ve seen this powershell message in other, related packages but I can`t say where / in which versions that was. Hence this delay in reporting back. I currently use both "Atom-shell" (Juno /LT) and "Atom". Juno/Lt complains that (electron) ipc module is deprecated, I should use ipcRenderer. Is this related? I looked for the option without finding what you mean.

**Comment by Varanas** [comment]
Is this still an issue, @hustf?

Juno/Atom is close to feature parity with Juno/LT, so I'd recommend using the former, especially since Juno/LT hasn't been updated in quite a while.

**Comment by hustf** [comment]
Varanas, thank you for following up. 

Atom has been working like a charm for two months, and it's pleasant to work with. I only leave the environment when I need speed, or better readability in help texts. Juno stopped working after an LT update, this is mentioned elsewhere I believe. I have not actively updated lately and so I look forward to finding out about the new features.

To check if all is really really fixed we would need to fiddle with variables and user privileges, which is very time consuming due to the restarts involved. To new users who might perhaps run into this or a related issue, it would be a much bigger pain of course. So if I can be of any assistance with testing, just ask, otherwise I believe this can be closed.

**Comment by Varanas** [comment]
Alright, glad it's working for you! Any specific issues with speed you're experiencing; if so, could you open an issue? The doc system will hopefully get a lot nicer soonish.

I'll close this -- if someone else experiences this they can just reopen or create a new issue.

**Comment by MikeInnes** [comment]
@hustf Yes, thanks very much for the offer of assistance, but as @Varanas says I think we shouldn't take up your time now – we can always ping if this comes up again in case you're able to help out.
