### ISSUE TITLE
Failed to load the julia-client package

### ISSUE THREAD

**Issue by SebastianM-C** [JunoLab/atom-julia-client#570]
Steps to reproduce

1. Start Atom with julia-client 0.8.10

**Atom**: 1.38.2 x64
**Electron**: 4.2.6
**OS**: "Antergos Linux"
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.8.10

### Stack Trace

Failed to load the julia-client package

```
At The module '/home/sebastian/.atom/packages/julia-client/node_modules/node-pty-prebuilt/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Error: The module '/home/sebastian/.atom/packages/julia-client/node_modules/node-pty-prebuilt/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/julia-client/node_modules/node-pty-prebuilt/lib/unixTerminal.js:22:11)
    at /packages/julia-client/node_modules/node-pty-prebuilt/lib/unixTerminal.js:266:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/julia-client/node_modules/node-pty-prebuilt/lib/index.js:13:20)
    at /packages/julia-client/node_modules/node-pty-prebuilt/lib/index.js:50:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/julia-client/lib/connection/process/basic2.js:3:24)
    at /packages/julia-client/lib/connection/process/basic2.js:174:2)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-latex 0.8.6 
ftp-remote-edit 0.16.3 
highlight-selected 0.16.0 
Hydrogen 2.10.3 
indent-detective 0.3.3 
ink 0.10.11 
julia-client 0.8.10 
language-fortran 2.1.8 
language-julia 0.19.1 
language-latex 1.2.0 
language-weave 0.6.4 
latex 0.50.2 
latex-completions 0.3.6 
markdown-preview-plus 3.8.1 
minimap 4.29.9 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
pdf-view 0.71.0 
split-diff 1.6.0 
tool-bar 1.1.11 
uber-juno 0.2.0 
wakatime 7.1.1 
```

**Comment by pfitzseb** [comment]
This is an issue with https://github.com/daviwil/node-pty-prebuilt not providing binaries for newer node versions (as well as node-pty versions).
For now your best bet is to run the officially supported Atom versions.

**Comment by alyst** [comment]
I have the same issue on ArchLinux, which uses _electron_ v5.0.6 at the moment (both _atom_ and _electron_ are from the official ArchLinux repository).
Is there any workaround that doesn't require downgrading atom/electron?

**Comment by benjamimo** [comment]
I have faced the same issue... so far I've tried to downgrade electron, atom, npm and julia-client, but without success (I'm running Manjaro).  Could someone point me in the right direction to have a functional Juno again?

**Comment by alyst** [comment]
FWIW, I've (temporary) switched to *vscode* with *julia* extension.

**Comment by pfitzseb** [comment]
The recommend fix is to use the official Atom binaries, not those in AUR etc.
Otherwise you can change [this line](https://github.com/JunoLab/atom-julia-client/blob/master/package.json#L18) to `node-pty` and search and replace all occurences of `node-pty-prebuilt` with `node-pty` in this repo.

**Comment by benjamimo** [comment]
Thanks for your help!  I found another way of getting a working Juno again, maybe is not advisable since it relies in using AUR.  Anyway, I installed the package atom-editor-bin from AUR and now everything is back to normal.  I'm not a huge fan of using AUR packages, but in this case it worked.

**Comment by pfitzseb** [comment]
Should be fixed with julia-client 0.8.12-beta2. Requires Atom 1.39 or newer, so please update (or use `apm install julia-client@0.8.13-beta2`).

**Comment by pglira** [comment]
I'm using atom 1.39.1 and julia-client 0.9.4, but the issue still shows up.


**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 14.04.6
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.9.4


### Stack Trace

Failed to load the julia-client package

```
At Cannot find module '../build/Debug/pty.node'

Error: Cannot find module '../build/Debug/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at Object.loadNative (/packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/utils.js:22:16)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:24:19)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/unixTerminal.js:255:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:14:20)
    at /packages/julia-client/node_modules/@pfitzseb/node-pty-prebuilt/lib/index.js:52:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at /packages/julia-client/lib/connection/process/basic2.js:3:24)
    at /packages/julia-client/lib/connection/process/basic2.js:174:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
```

### Commands

```
```

### Non-Core Packages

```
indent-detective 0.4.0 
ink 0.10.12 
julia-client 0.9.4 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```
